name: Laravel-CI

#Laravel CI

on:
  push:
    branches: [master, dev, release/*, feature/*]
  pull_request:
    branches: [master, dev, release/*, feature/*]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: homestead
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
        with:
          php-version: "7.4"
          extensions: mbstring, pdo_sqlite, fileinfo, gd, xdebug, bcmath
          coverage: xdebug
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Migrate Database
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: homestead
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: secret
        run: php artisan migrate
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: homestead
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: secret
        run: vendor/bin/phpunit
